/**
 * @dotdo/vitess-rpc
 *
 * CapnWeb RPC protocol and unified types for Vitess.do
 */

// Types
export type {
  StorageEngineType,
  Row,
  Field,
  QueryResult,
  ExecuteResult,
  BatchResult,
  ShardId,
  Keyspace,
  VindexType,
  VindexDef,
  TableDef,
  VSchema,
  IsolationLevel,
  TransactionOptions,
  ShardHealth,
  ClusterStatus,
  QueryTarget,
  AggregateFunction,
  AggregateSpec,
} from './types.js';

// Type guards from types.ts
export {
  isRow,
  isField,
  isQueryResult,
  isExecuteResult,
  isBatchResult,
  isShardHealth,
  isClusterStatus,
  isStorageEngineType,
  isVindexType,
  isKeyspace,
  isVindexDef,
  isTableDef,
  isVSchema,
  isIsolationLevel,
  isTransactionOptions,
  isQueryTarget,
  isAggregateFunction,
  isAggregateSpec,
  validateField,
  validateQueryResult,
  validateExecuteResult,
  validateKeyspace,
  validateVindexDef,
  validateTableDef,
  validateVSchema,
} from './types.js';

// Protocol
export {
  MessageType,
  createMessageId,
  createQueryRequest,
  createExecuteRequest,
  createErrorResponse,
  createBatchRequest,
  createBeginRequest,
  createCommitRequest,
  createRollbackRequest,
  createStatusRequest,
  createHealthRequest,
  createSchemaRequest,
  createVSchemaRequest,
  createShardQueryRequest,
  createShardExecuteRequest,
  createShardBatchRequest,
  createQueryResponse,
  createExecuteResponse,
  createBatchResponse,
  createBeginResponse,
  createStatusResponse,
  createHealthResponse,
  createSchemaResponse,
  createVSchemaResponse,
  createAckResponse,
  isRpcMessage,
  isQueryRequest,
  isExecuteRequest,
  isBatchRequest,
  isBeginRequest,
  isCommitRequest,
  isRollbackRequest,
  isStatusRequest,
  isHealthRequest,
  isSchemaRequest,
  isVSchemaRequest,
  isShardQueryRequest,
  isShardExecuteRequest,
  isShardBatchRequest,
  isQueryResponse,
  isExecuteResponse,
  isBatchResponse,
  isBeginResponse,
  isStatusResponse,
  isHealthResponse,
  isSchemaResponse,
  isVSchemaResponse,
  isErrorResponse,
  isAckResponse,
  isRequest,
  isResponse,
} from './protocol.js';

export type {
  RpcMessage,
  QueryRequest,
  ExecuteRequest,
  BatchRequest,
  BeginRequest,
  CommitRequest,
  RollbackRequest,
  StatusRequest,
  HealthRequest,
  SchemaRequest,
  VSchemaRequest,
  ShardQueryRequest,
  ShardExecuteRequest,
  ShardBatchRequest,
  QueryResponse,
  ExecuteResponse,
  BatchResponse,
  BeginResponse,
  StatusResponse,
  HealthResponse,
  SchemaResponse,
  VSchemaResponse,
  ErrorResponse,
  AckResponse,
  Request,
  Response,
} from './protocol.js';

// Serialization
export {
  serializeRequest,
  serializeResponse,
  serializeMessage,
  deserializeRequest,
  deserializeResponse,
  deserializeMessage,
  safeJsonParse,
  safeJsonStringify,
} from './serialization.js';
